apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    app: alertmanager
    alertmanager: main
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'telegram'
    receivers:
    - name: 'telegram'
      webhook_configs:
      - url: 'http://alertgram:8080/alerts'
        send_resolved: false
